name: Render Quarto Website

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - uses: quarto-dev/quarto-actions/setup@v3

      - name: Install R
        uses: r-lib/actions/setup-r@v2

      - name: Install R packages
        run: |
          install.packages("tidyverse")
          install.packages("sf")
          install.packages("readr")

      - name: Render
        uses: quarto-dev/quarto-actions/render@v3
